### ISSUE TITLE
Remove dependency on registry_autoload

### ISSUE THREAD

**Issue by angry-dan** [Plug-Drupal/plug#43]
I already use xautoload elsewhere in my code and therefore don't have a need for registry_autoload. Could you remove the dependency please?

**Comment by e0ipso** [comment]
It's a bit complex to have conditional dependencies enforced. You need either one or the other, but you need one.

I have the opinion that `registry_autoload` outperforms `xautoload`, that's why I chose to depend on that one.

If you have a good solution to require at least one of the two, please submit a PR. FYI `hook_requirements` will not really work since it does not enforce dependencies.

**Comment by angry-dan** [comment]
Looking again it would seem that /lib is treated differently by the two modules and you get a class not found error if you don't have registry_autoload. It's a shame for sure, although maybe I should just go with registry_autoload. Xautoload has always seemed like the more comprehensive solution, especially given the caching options it provides and the ability to replace the internal loading system.

**Comment by e0ipso** [comment]
If you don't mind getting stuck in an old version of the module you can use https://github.com/Plug-Drupal/plug/tree/d6de058aca65ffb6b0739889757430527d622011

That old version is using XAutoload.
